import g4p_controls.*;

PImage img;
OutputStream os;

void setup(){
  size(400,200);
  createGUI();
}
int i=0;
void draw(){
  
}

int c24toc8(int r,int g,int b){
  int encodedData = (floor((r / 32)) << 5) + (floor((g / 32)) << 2) + floor((b / 64));
  return encodedData;
}

void conv(){
  img=loadImage(textfield1.getText());
  int[] imageRes=int(split(ImageRes.getText(),'x'));
  int[] scrRes=int(split(SRES.getText(),'x'));
  int[] scrNum=int(split(SNUM.getText(),'x'));
  img.resize(imageRes[0],imageRes[1]);
  img.copy(img, scrNum[0],scrNum[1], scrRes[0],scrRes[1], 0,0, imageRes[0],imageRes[1]);
  img.resize(scrRes[0],scrRes[1]);
  os=createOutput(textfield2.getText());
  
  try{
    os.write((char)img.width);
    os.write((char)img.height);
  }catch(Exception e){}
  for(int y=0;y<img.height;y+=2)
    for(int x=0;x<img.width;x++){
      println(x+"\t"+y);
      color col=img.get(x,y);
      color col2=img.get(x,y+1);
      try{
        os.write((char)red(col));
        os.write((char)green(col));
        os.write((char)blue(col));
        
        os.write((char)red(col2));
        os.write((char)green(col2));
        os.write((char)blue(col2));
      }catch(Exception e){}
    }
  try{os.close();}catch(Exception e){}
}

void selIFile(File f){
  if(f!=null){
    textfield1.setText(f.getAbsolutePath());
  }
}

void selOFile(File f){
  if(f!=null){
    textfield2.setText(f.getAbsolutePath());
  }
}

/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void SelInputFile(GButton source, GEvent event) { //_CODE_:button1:369845:
  selectInput("Select image","selIFile");
} //_CODE_:button1:369845:

public void SelOutFile(GButton source, GEvent event) { //_CODE_:button2:933435:
  selectOutput("Select output OCIF","selOFile");
} //_CODE_:button2:933435:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:SRES:778469:
  println("SRES - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:SRES:778469:

public void textfield1_change2(GTextField source, GEvent event) { //_CODE_:textfield1:582040:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:582040:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:798739:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:798739:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:870008:
  conv();
} //_CODE_:button3:870008:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:SNUM:960602:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:SNUM:960602:

public void textfield3_change2(GTextField source, GEvent event) { //_CODE_:ImageRes:421861:
  println("ImageRes - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:ImageRes:421861:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 10, 10, 120, 20);
  button1.setText("Select input file");
  button1.addEventHandler(this, "SelInputFile");
  button2 = new GButton(this, 10, 40, 120, 20);
  button2.setText("Select output file");
  button2.addEventHandler(this, "SelOutFile");
  SRES = new GTextField(this, 10, 130, 380, 20, G4P.SCROLLBARS_NONE);
  SRES.setPromptText("Screen resolution (100x100 (up to 160x50))");
  SRES.setLocalColorScheme(GCScheme.RED_SCHEME);
  SRES.setOpaque(true);
  SRES.addEventHandler(this, "textfield1_change1");
  textfield1 = new GTextField(this, 140, 10, 250, 20, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change2");
  textfield2 = new GTextField(this, 140, 40, 250, 20, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  button3 = new GButton(this, 10, 160, 380, 30);
  button3.setText("Convert");
  button3.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button3.addEventHandler(this, "button3_click1");
  SNUM = new GTextField(this, 10, 100, 380, 20, G4P.SCROLLBARS_NONE);
  SNUM.setPromptText("Start pixel (100x100,100x200 (up to 300x300))");
  SNUM.setLocalColorScheme(GCScheme.RED_SCHEME);
  SNUM.setOpaque(true);
  SNUM.addEventHandler(this, "textfield3_change1");
  ImageRes = new GTextField(this, 10, 70, 380, 20, G4P.SCROLLBARS_NONE);
  ImageRes.setPromptText("Output image resolution (100x100, 200x100)");
  ImageRes.setLocalColorScheme(GCScheme.RED_SCHEME);
  ImageRes.setOpaque(true);
  ImageRes.addEventHandler(this, "textfield3_change2");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GTextField SRES; 
GTextField textfield1; 
GTextField textfield2; 
GButton button3; 
GTextField SNUM; 
GTextField ImageRes; 
